from .patterns import (
    SQL_KEYWORDS, DANGEROUS_FUNCS, INPUT_FUNCTIONS,
    INPUT_METHODS, SECRET_PATTERNS, HTML_SINKS,
)

__all__ = [
    "SQL_KEYWORDS", "DANGEROUS_FUNCS", "INPUT_FUNCTIONS",
    "INPUT_METHODS", "SECRET_PATTERNS", "HTML_SINKS",
]
